version: "3"
services:
  db:
    image: postgres
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "pg_isready",
    #       "-q",
    #       "-d",
    #       "postgres",
    #       "-U",
    #       "root"
    #     ]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10
    container_name: "pg_container"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data/
